Repository thebjko/Boss, pull requests merged in 2023-05, with the labels that each got.

#1 update accounts/models.py - User
  accounts/admin.py
  accounts/models.py
  config/settings/base.py
Labels: enhancement

#2 Create models 상품, 카테고리, 서브카테고리, 상세카테고리, 리뷰
  boss/models.py
Labels: documentation

#4 Update model 이미지 필드 추가 , 상세 카테고리 삭제, admin.py 수정
  boss/admin.py
  boss/models.py
Labels: enhancement

#3 boss_base_view,form,urls
  boss/forms.py
  boss/urls.py
  boss/views.py
Labels: enhancement

#5 Accounts
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#6 Feature/navbar
  boss/templates/boss/index.html
  boss/urls.py
  boss/views.py
  static/image/logo.png
  static/main/navbar.css
  templates/base.html
Labels: enhancement

#7 상품_디테일페이지_구현시작
  boss/templates/boss/detail.html
Labels: enhancement

#9 boss/create 임시생성
  boss/forms.py
  boss/templates/boss/create.html
  boss/urls.py
  boss/views.py
Labels: enhancement

#12 add category, subcategory fixture files
  boss/fixtures/categories.json
  boss/fixtures/subcategories.json
  config/settings/base.py
Labels: enhancement

#14 Create discord.yml
  .github/workflows/discord.yml
Labels: enhancement

#15 review
  accounts/migrations/0001_initial.py
  boss/forms.py
  boss/migrations/0001_initial.py
  boss/urls.py
  boss/views.py
Labels: enhancement

#17 update discord.yml - substitute deprecated command
  .github/workflows/discord.yml
Labels: enhancement

#21 review 다중이미지 업로드, #11 해결
  boss/__init__.py
  boss/apps.py
  boss/forms.py
  boss/models.py
  boss/signals.py
  boss/templates/boss/review_create.html
  boss/views.py
Labels: documentation, enhancement

#22 Index
  accounts/migrations/0001_initial.py
  boss/admin.py
  boss/migrations/0001_initial.py
  boss/migrations/0002_auto_20230510_1312.py
  boss/migrations/0003_review_like_users.py
  boss/models.py
  boss/static/boss/images/index_carousel/carousel1.gif
  boss/static/boss/images/index_carousel/carousel10.webp
  boss/static/boss/images/index_carousel/carousel11.webp
  boss/static/boss/images/index_carousel/carousel2.webp
  boss/static/boss/images/index_carousel/carousel3.webp
  boss/static/boss/images/index_carousel/carousel4.gif
  boss/static/boss/images/index_carousel/carousel5.webp
  boss/static/boss/images/index_carousel/carousel6.webp
  boss/static/boss/images/index_carousel/carousel7.webp
  boss/static/boss/images/index_carousel/carousel8.webp
  boss/static/boss/images/index_carousel/carousel9.webp
  boss/templates/boss/index.html
  boss/templates/boss/index_components/index_carousel.html
  boss/views.py
  config/urls.py
Labels: enhancement

#23 refactor first carousel-item
  boss/templates/boss/index_components/index_carousel.html
Labels: enhancement

#24 Add review update
  boss/signals.py
  boss/templates/boss/review_update.html
  boss/urls.py
  boss/views.py
Labels: enhancement

#27 상품 상세페이지 수정
  boss/templates/boss/detail.html
Labels: enhancement

#28 리뷰 리스트 소프트코딩, 좋아요 연결
  boss/templates/boss/detail.html
  boss/urls.py
  boss/views.py
  templates/base.html
Labels: enhancement

#29 Feature/category
  static/image/favicon.png
  static/main/main.js
  static/main/navbar.css
  templates/base.html
  templates/category.html
Labels: enhancement

#30 add category click event
  static/main/main.js
  static/main/navbar.css
  templates/category.html
Labels: enhancement

#32 Re fixtures
  boss/fixtures/categories_re.json
  boss/fixtures/subcategories_re.json
Labels: duplicate, enhancement

#34 프로필 페이지 초안
  accounts/templates/accounts/profile.html
  static/image/no_product.png
Labels: enhancement

#33 Fix main.js
  static/main/main.js
Labels: enhancement

#35 Add product fixtures (sausage)
  boss/fixtures/product1_sausage.json
  boss/views.py
Labels: enhancement

#37 add field to product model
  boss/models.py
Labels: enhancement

#38 search_filter
  boss/forms.py
  boss/migrations/0002_auto_20230511_1101.py
  boss/models.py
  boss/templates/boss/search.html
  boss/views.py
  templates/base.html
Labels: enhancement

#39 Django와 MySQL 연결
  Pipfile
  Pipfile.lock
  config/settings/base.py
  config/settings/db-test.py
  config/settings/dev.py
  config/settings/prod.py
  requirements.txt
Labels: enhancement

#42 Pty9714/search
  boss/templates/boss/create.html
  boss/urls.py
  boss/views.py
Labels: enhancement

#43 회원가입 페이지 완성
  accounts/forms.py
  accounts/templates/accounts/signup.html
Labels: enhancement

#41 add events field to Product
  boss/models.py
Labels: 수정사항

#45 로그인링크_임시연결
  templates/navbar.html
Labels: enhancement

#46 로그인 링크수정
  templates/navbar.html
Labels: enhancement

#47 Thebjko/hotfix base settings
  config/settings/base.py
  config/settings/dev.py
  config/settings/prod.py
Labels: hotfix

#48 Thebjko/add strict option
  boss/migrations/0003_auto_20230512_1123.py
  config/settings/base.py
Labels: enhancement

#49 [Rabbit64/index] index 페이지에 들어가는 이미지 파일 업로드, index body content1, 네브바 수정
  accounts/migrations/0001_initial.py
  boss/fixtures/product1_sausage_re.json
  boss/fixtures/product1_sausage_re2.json
  boss/fixtures/product1_sausage_re3.json
  boss/migrations/0001_initial.py
  boss/migrations/0002_auto_20230511_1101.py
  boss/models.py
  boss/templates/boss/index.html
  boss/views.py
  media/products/식자재민족/도매순살치킨_1KG
  media/products/식자재민족/도매순살치킨_1KG_aAYr3CL
  media/products/식자재민족/먹깨비네_진주햄_골드_스모크햄_1kgx1개냉장
  media/products/식자재민족/먹깨비네_진주햄_골드_스모크햄_1kgx1개냉장_EQ18mFS
  media/products/식자재민족/사세통상 순살치킨가라아게(냉동 1kg/ea
  media/products/식자재민족/사세통상 순살치킨가라아게(냉동 1kg/ea_Wam0S9h
  media/products/식자재민족/상도_닭똥집_튀김_1kg
  media/products/식자재민족/상도_닭똥집_튀김_1kg_a1CR1sy
  media/products/식자재민족/순살치킨_해마로_1kg_냉동
  media/products/식자재민족/순살치킨_해마로_1kg_냉동_DELqVbJ
  media/products/식자재민족/아워홈_그릴드_치킨브레스트_1kg_냉장
  media/products/식자재민족/아워홈_그릴드_치킨브레스트_1kg_냉장_ByM7NgI
  media/products/식자재민족/에쓰푸드_보스턴핫_소시지_300g
  media/products/식자재민족/에쓰푸드_보스턴핫_소시지_300g_loOgoEJ
  media/products/식자재민족/에쓰푸드_통삼겹_차슈_700g
  media/products/식자재민족/에쓰푸드_통삼겹_차슈_700g_DZvWMQm
  media/products/식자재민족/직배송식자재왕_함박스테이크더블_1kg
  media/products/식자재민족/직배송식자재왕_함박스테이크더블_1kg_a5tFlmO
  media/products/식자재민족/택배식자재왕_양념편육_430g
  media/products/식자재민족/택배식자재왕_양념편육_430g_CssPXEe
  static/main/index.css
  static/main/navbar.css
  templates/base.html
Labels: enhancement

#50 Thebjko/model change
  boss/forms.py
  boss/migrations/0001_initial.py
  boss/migrations/0003_auto_20230512_1123.py
  boss/models.py
Labels: enhancement

#51 Rab bit64/index
  accounts/migrations/0001_initial.py
  boss/fixtures/product1_sausage_re3.json
  boss/models.py
  boss/templates/boss/index.html
  boss/views.py
  static/main/index.css
  static/main/main.js
Labels: enhancement

#52 로그인_페이지구현
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/views.py
  static/image/kakao.png
  templates/navbar.html
Labels: enhancement

#54 Product 모델 one_plus_one 필드 삭제 후 Fixtures 파일 정리
  boss/fixtures/categories.json
  boss/fixtures/categories_re.json
  boss/fixtures/product1_sausage.json
  boss/fixtures/product1_sausage_re.json
  boss/fixtures/product1_sausage_re2.json
  boss/fixtures/product1_sausage_re3.json
  boss/fixtures/products.json
  boss/fixtures/subcategories.json
  boss/fixtures/subcategories_re.json
  boss/fixtures/users.json
  boss/migrations/0001_initial.py
  boss/migrations/0002_remove_product_one_plus_one.py
  boss/models.py
Labels: DB 관련

#56 filter
  boss/models.py
  boss/templates/boss/search.html
  boss/views.py
  templates/base.html
Labels: enhancement

#58 Cart, Kakaopay
  accounts/views.py
  boss/templates/boss/detail.html
  cart/__init__.py
  cart/admin.py
  cart/apps.py
  cart/context_processors.py
  cart/migrations/0001_initial.py
  cart/migrations/__init__.py
  cart/models.py
  cart/static/cart/css/cart_deatil.css
  cart/templates/cart/cart.html
  cart/tests.py
  cart/urls.py
  cart/views.py
  config/settings/base.py
  config/urls.py
  kakaopay/__init__.py
  kakaopay/admin.py
  kakaopay/apps.py
  kakaopay/migrations/__init__.py
  kakaopay/models.py
  kakaopay/static/kakaopay/css/approval.css
  kakaopay/static/kakaopay/image/pay2.png
  kakaopay/static/kakaopay/js/approval.js
  kakaopay/static/kakaopay/js/pay_cancel.js
  kakaopay/static/kakaopay/js/pay_fail.js
  kakaopay/static/kakaopay/js/wait.js
  kakaopay/templates/kakaopay/approval.html
  kakaopay/templates/kakaopay/index.html
  kakaopay/templates/kakaopay/pay_cancel.html
  kakaopay/templates/kakaopay/pay_fail.html
  kakaopay/templates/kakaopay/wait.html
  kakaopay/tests.py
  kakaopay/urls.py
  kakaopay/views.py
  requirements.txt
  templates/navbar.html
Labels: enhancement

#57 Thebjko/index data for sections
  Pipfile
  Pipfile.lock
  accounts/migrations/0002_alter_user_followers.py
  accounts/migrations/0003_remove_user_followers.py
  accounts/migrations/0004_user_followers.py
  boss/migrations/0001_initial.py
  boss/migrations/0002_address_order.py
  boss/migrations/0003_auto_20230513_0850.py
  boss/migrations/0004_auto_20230513_0920.py
  boss/models.py
  boss/templates/boss/index.html
  boss/templates/boss/index_components/section.html
  boss/views.py
  requirements.txt
Labels: enhancement

#59 search
  accounts/migrations/0001_initial.py
  boss/migrations/0001_initial.py
  boss/models.py
  boss/templates/boss/search.html
  boss/views.py
  templates/base.html
Labels: enhancement

#61 상품 생성 페이지_수정중
  boss/forms.py
  boss/migrations/0001_initial.py
  cart/migrations/0001_initial.py
Labels: enhancement

#63 상품 생성 페이지_1차
  boss/forms.py
  boss/templates/boss/create.html
Labels: enhancement

#64 Thebjko/product add rating
  Pipfile
  Pipfile.lock
  boss/migrations/0005_review_rating.py
  boss/models.py
  boss/templates/boss/detail.html
  boss/views.py
  config/settings/dev.py
  config/urls.py
  requirements2.txt
Labels: enhancement

#65 카테고리 페이지
  boss/templates/boss/category_products.html
  boss/templates/boss/detail.html
  boss/templates/boss/subcategory_products.html
  boss/urls.py
  boss/views.py
  static/main/navbar.css
  templates/category.html
Labels: enhancement
